name: external echo command from container

on:
  repository_dispatch:
    types: [container-echo]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: lambci/lambda:build-python3.7@sha256:3cfeb4c0d8fe26588918720014f13018b8c50bad89fdd5aa7ac58c25f90869ae

    steps:
    - uses: actions/checkout@v2
      with:
        path: test 
    - name: echo from container
      run: |
        echo hello from container land
        pwd
        ls -l $HOME
        echo $HOME
        ls -l
        echo 'test/'
        ls -l /test
        echo "github/home"
        #ls -l /
        #ls -l /github
        ls -l /github/home
        echo "github/workflow"
        ls -l /github/workflow
        python --version
        cat output.txt
