name: external echo command

on:
  pull_request:
    branches:
      - master
  repository_dispatch:
    types: [external-echo]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cat repo file
      run: |
        pwd
        ls -la
        cat output.txt
        cat ${{ github.workspace}}/output.txt
