name: external echo command

on:
  pull_request:
    branches:
      - master
  repository_dispatch:
    types: [external-echo]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: echo
      run: echo externally executed echo
