name: external echo command

on:
  pull_request:
    branches:
      - master
  repository_dispatch:
    types: [external-echo]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
    - name: cat repo file
      run: cat output.txt
=======
    - name: echo
      run: echo externally executed echo updated
>>>>>>> test pr
