name: external echo command

on:
  pull_request:
    branches:
      - master
  repository_dispatch:
    types: [external-echo]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: cat repo file
      run: |
        pwd
        ls -la
        ls -la ../
        cat /github/workspace/output.txt
        cat ${{ github.workspace	}}/output.txt
