name: multi dir repo dispatch with a single step

on:
  repository_dispatch:
    types: [multi-dispatch-single-step]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.ref }}

    - name: cat repo file
      run: cat output.txt
      working-directory: ${{ github.event.client_payload.project }}