name: echo chamber

on:
  issue_comment:
    types: [created]

jobs:
  echo-chamber:
    if: >
      startsWith(github.event.comment.body, 'echo')
      && startsWith(github.event.issue.pull_request.url, 'https://')

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.ref }}

    - name: multiply in tunnel
      id: tunnel
      run: |
        bash -x scripts/write_comment.sh

    - uses: actions/github-script@v2
      env:
        output: ${{ steps.tunnel.outputs.reverb }}
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "The these lambda versions have been updated:" +
            process.env.output
            })