name: echo chamber

on:
  issue_comment:
    types: [created]

jobs:
  echo-chamber:
    if: >
      startsWith(github.event.comment.body, 'echo')
      && startsWith(github.event.issue.pull_request.url, 'https://')

    runs-on: ubuntu-latest

    steps:
    - name: print comment body
      run: echo ${{ github.event.comment.body }}

    - name: set body comments
      id: listen
      run: |
        set -eu
        content=$( cut -d ' ' -f 2 <<< '${{ github.event.comment.body }}' )
        echo "::set-output name=content::$content"

    - name: write a comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ github.event.comment.id }}
        body: |
           ${{ steps.listen.outputs.content }}

