name: echo chamber

on:
  issue_comment:
    types: [created]

jobs:
  build:
    if: >
      startsWith(github.event.comment.body, 'echo')
      && startsWith(github.event.issue.pull_request.url, 'https://')

    runs-on: ubuntu-latest

    steps:
    - name: print comment body
      run: echo ${{ github.event.comment.body }}

    - name: set body comments
      run: |
        set -eu
        content=$( cut -d ' ' -f 2 <<< '${{ github.event.comment.body }}' )
        echo $content

    - name: write a comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ github.event.comment.id }}
        body: "test"

    # - name: 'Load PR Details'
    #   id: load-pr
    #   run: |
    #     set -eu
    #     resp=$(curl -sSf \
    #       --url ${{ github.event.issue.pull_request.url }} \
    #       --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
    #       --header 'content-type: application/json')
    #     echo $resp
    #     branch=$(jq -r '.head.ref' <<< "$resp")
    #     echo "::set-output name=branch::$branch"

    # - uses: actions/checkout@v2
    #   with:
    #     ref: ${{ github.event.client_payload.ref }}

    # - name: cat repo file
    #   run: cat output.txt
    #   working-directory: ${{ github.event.client_payload.project }}
