name: multi dir repo dispatch

on:
  repository_dispatch:
    types: [print-workspace]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: echo workspace before
      run: echo ${{ GITHUB_WORKSPACE }}


    - uses: actions/checkout@v2

    - name: echo workspace after
      run: echo ${{ GITHUB_WORKSPACE }}
