name: external echo command

on:
  repository_dispatch:
    types: [my-dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.ref }}

    - name: cat repo file
      run: cat output.txt
