name: test checkout on diff versions

on:
  issue_comment:
    types: [created]

jobs:
  build:

    if: >
      startsWith(github.event.comment.body, 'build')
      && startsWith(github.event.issue.pull_request.url, 'https://')
    runs-on: ubuntu-latest
    container:
      image: drewmullen/lambda-build-python:0.1
    steps:

      - name: echo
        run: |
          echo something

      - name: 'Checkout from PR Branch'
        uses: actions/checkout@v2.3.2
        with:
          ref: b034ce5b441f83860e844628e1086e1bb29452b0
