name: test checkout on diff versions

# lambda-build.yml overview:
#
# Github Actions event listener for PR comments. L23 declares comment content to trigger workflow
#  Comment Format:
#  build <build directory> <buckets space separated>
#
#  Ex of PR comment:
#  build awslambda/asg_ebs_attach bucket1 bucket2
#
#  above will build the lambda bundle for asg_ebs_attach and publish it to bucket{1,2}

on:
  issue_comment:
    types: [created]

jobs:
  build:

    if: >
      startsWith(github.event.comment.body, 'build')
      && startsWith(github.event.issue.pull_request.url, 'https://')
    runs-on: ubuntu-latest
    container:
      image: alpine/git
    steps:

      - name: 'Checkout from PR Branch'
        uses: actions/checkout@v2
