name: test checkout on diff versions

# lambda-build.yml overview:
#
# Github Actions event listener for PR comments. L23 declares comment content to trigger workflow
#  Comment Format:
#  build <build directory> <buckets space separated>
#
#  Ex of PR comment:
#  build awslambda/asg_ebs_attach bucket1 bucket2
#
#  above will build the lambda bundle for asg_ebs_attach and publish it to bucket{1,2}

on:
  issue_comment:
    types: [created]

jobs:
  build:

    if: >
      startsWith(github.event.comment.body, 'build')
      && startsWith(github.event.issue.pull_request.url, 'https://')
    runs-on: ubuntu-latest
    container:
      image: alpine/git
    steps:

      - name: 'Load PR Details'
        id: load-pr
        run: |
          set -eu
          resp=$(curl -sSf \
            --url ${{ github.event.issue.pull_request.url }} \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type: application/json')
          branch=$(python3 -c "import sys, json; print(json.load(sys.stdin)['head']['ref'])" <<< "$resp")
          echo "::set-output name=branch::$branch"

      - name: Pulls Repository Code
        uses: actions/checkout@28c7f3d2
        with:
          ref: ${{ steps.load-pr.outputs.branch }}

      - name: 'Checkout from PR Branch'
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.load-pr.outputs.branch }}
          token: ${{ secrets.REPO_PAT }}
